[build]
  publish = "."
  command = "echo 'Static site deployment'"

[build.environment]
  PYTHON_VERSION = "3.9"

# API redirects to serverless functions
[[redirects]]
  from = "/api/available-dates"
  to = "/.netlify/functions/available-dates"
  status = 200

[[redirects]]
  from = "/api/company-news/*"
  to = "/.netlify/functions/company-news"
  status = 200

[[redirects]]
  from = "/api/company-details/*/*"
  to = "/.netlify/functions/company-details"
  status = 200

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200