[build]
  publish = "."

[[redirects]]
  from = "/api/available-dates"
  to = "/.netlify/functions/available-dates"
  status = 200

[[redirects]]
  from = "/api/company-news/*"
  to = "/.netlify/functions/company-news"
  status = 200

[[redirects]]
  from = "/api/company-details/*/*"
  to = "/.netlify/functions/company-details"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200